version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: sail
        uid: 1000
    image: sail-app
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy

  vite:
    image: node:18
    container_name: vite
    restart: unless-stopped
    ports:
      - "5173:5173"
    working_dir: /var/www
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./:/var/www
    networks:
      - sail

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: '${DB_PASSWORD}'
      UPLOAD_LIMIT: 300M
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
